-- Seed: items (from جدول_زمني_شامل_كل_البنود.xlsx)
insert into items (phase, order_no, name, planned_start_date, duration_days, total_qty, unit) values
('foundations_only', 1, 'شراء الارض', '2026-06-30', 0.0, NULL, NULL),
('foundations_only', 2, 'الصك', NULL, NULL, NULL, NULL),
('foundations_only', 3, 'اعمال الرفع المساحي حدود ومناسيب الشارع', NULL, NULL, NULL, NULL),
('foundations_only', 4, 'السور المؤقت', NULL, NULL, NULL, NULL),
('foundations_only', 5, 'جسات التربة', NULL, NULL, NULL, NULL),
('foundations_only', 6, 'مرحلة التخطيط والتصميم والرخصة', NULL, NULL, NULL, NULL),
('foundations_only', 7, 'مرحلة حفر الارض للوصول الى منسوب التصميم', NULL, NULL, NULL, NULL),
('foundations_only', 8, 'أعمال حفر - الخزانات والبيارات', NULL, NULL, NULL, NULL),
('foundations_only', 9, 'مرحلة الاحلال  والرص والاختبارات + اختبار التحميل اللوحي', NULL, NULL, NULL, NULL),
('foundations_only', 10, 'صبة نظافة الخزانات والبيارات', NULL, NULL, NULL, NULL),
('foundations_only', 11, 'مباني الخزانات والبيارات', NULL, NULL, NULL, NULL),
('foundations_only', 12, 'عزل الخزانات والبيارات', NULL, NULL, NULL, NULL),
('foundations_only', 13, 'صبة اللبشة خزانات والبيارات', NULL, NULL, NULL, NULL),
('foundations_only', 14, 'حددة ونجارة الدران والدفان حول جدران الخزانات والبيارات', NULL, NULL, NULL, NULL),
('foundations_only', 15, 'صبة جدران الخزانات والبيارات', NULL, NULL, NULL, NULL),
('foundations_only', 16, 'صبة سقف الخزانات والبيارات', NULL, NULL, NULL, NULL),
('foundations_only', 17, 'استكمال احلال الموقع في الاماكن المجاورة للخزانات والبيارات', NULL, NULL, NULL, NULL),
('foundations_only', 18, 'اعمال الرص وصبة النظافة', NULL, NULL, NULL, NULL),
('foundations_only', 19, 'اعمال المباني لبشة القبو', NULL, NULL, NULL, NULL),
('foundations_only', 20, 'اعمال العزل لبشة القبو', NULL, NULL, NULL, NULL),
('foundations_only', 21, 'اعمال حدادة اللبشة - والتمديدات الميكانيكية وتسليم التأمين', NULL, NULL, NULL, NULL),
('foundations_only', 22, 'اعمال صبة اللبشة للقبو', NULL, NULL, NULL, NULL),
('foundations_only', 23, 'اعمال صبة اعمدة وجدران للقبو', NULL, NULL, NULL, NULL),
('foundations_only', 24, 'اعمال صبة سقف القبو', NULL, NULL, NULL, NULL),
('foundations_only', 25, 'اعمال عزل جدران القبو وبناء بلوك الحماية', NULL, NULL, NULL, NULL),
('foundations_only', 26, 'اعمال الدفان حول القبو', NULL, NULL, NULL, NULL),
('foundations_only', 27, 'صبة القواعد  ( نجارة حدادة -التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_only', 28, 'صبة الرقاب ( نجارة حدادة صب )', NULL, NULL, NULL, NULL),
('foundations_only', 29, 'العزل قواعد ورقاب', NULL, NULL, NULL, NULL),
('foundations_only', 30, 'الدفان ( شامل التوريد والرص والمختبر والتسليم )', NULL, NULL, NULL, NULL),
('foundations_only', 31, 'مباني كرسي الميدا - مع عزله من الاعلى بلفائف عزل', NULL, NULL, NULL, NULL),
('foundations_only', 32, 'صبة الميدا ( نجارة حدادة -التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_only', 33, 'فك الميدا', NULL, NULL, NULL, NULL),
('foundations_only', 34, 'عزل الميدا', NULL, NULL, NULL, NULL),
('foundations_only', 35, 'تمديدات الالكتروميكانية ( مع الاختبارات والتثبيت )', NULL, NULL, NULL, NULL),
('foundations_only', 36, 'الدفان بين الميدات   (شامل التوريد والرص والمختبر والتأمين )', NULL, NULL, NULL, NULL),
('foundations_only', 37, 'صبة الارضية بين الميدات ( رش مبيد بلاستيك حدادة صب )', NULL, NULL, NULL, NULL),
('foundations_only', 38, 'أعمدة الأرضي ( حدادة - نجارة - التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_only', 39, 'اسقف الأرضي  ( نجارة -حدادة -تمديدات - التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_only', 40, 'مباني الأرضي', NULL, NULL, NULL, NULL),
('foundations_only', 41, 'تأسيس كهرباء - قبل اللياسة', NULL, NULL, NULL, NULL),
('foundations_only', 42, 'تأسيس سباكة - قبل اللياسة', NULL, NULL, NULL, NULL),
('foundations_only', 43, 'تأسيس دفاع مدني - قبل اللياسة', NULL, NULL, NULL, NULL),
('foundations_only', 44, 'اختبار صرف التكييف - قبل اللياسة', NULL, NULL, NULL, NULL),
('foundations_only', 45, 'اعمال الطرطشة وتركيب الشبك والزوايا  وتقفيل المواسير', NULL, NULL, NULL, NULL),
('foundations_only', 46, 'اللياسة الداخلية', NULL, NULL, NULL, NULL),
('foundations_only', 47, 'الجبس', NULL, NULL, NULL, NULL),
('foundations_only', 48, 'الدهان الاوجه الاولى', NULL, NULL, NULL, NULL),
('foundations_only', 49, 'عزل الحمامات والمطابخ', NULL, NULL, NULL, NULL),
('foundations_only', 50, 'بلاط الارضيات والحمامات والجدران', NULL, NULL, NULL, NULL),
('foundations_only', 51, 'ابواب الشقق ( حديد )', NULL, NULL, NULL, NULL),
('foundations_only', 52, 'ابواب الغرف', NULL, NULL, NULL, NULL),
('foundations_only', 53, 'أعمدة الأول ( حدادة - نجارة - التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_only', 54, 'سقف الأول  ( نجارة -حدادة -تمديدات - التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_only', 55, 'مباني الأول', NULL, NULL, NULL, NULL),
('foundations_only', 56, 'تأسيس كهرباء', NULL, NULL, NULL, NULL),
('foundations_only', 57, 'تأسيس سباكة', NULL, NULL, NULL, NULL),
('foundations_only', 58, 'تأسيس دفاع مدني', NULL, NULL, NULL, NULL),
('foundations_only', 59, 'اختبار صرف التكييف', NULL, NULL, NULL, NULL),
('foundations_only', 60, 'اعمال الطرطشة وتركيب الشبك والزوايا  وتقفيل المواسير', NULL, NULL, NULL, NULL),
('foundations_only', 61, 'اللياسة الداخلية', NULL, NULL, NULL, NULL),
('foundations_only', 62, 'الجبس', NULL, NULL, NULL, NULL),
('foundations_only', 63, 'الدهان الاوجه الاولى', NULL, NULL, NULL, NULL),
('foundations_only', 64, 'عزل الحمامات والمطابخ', NULL, NULL, NULL, NULL),
('foundations_only', 65, 'بلاط الارضيات والحمامات والجدران', NULL, NULL, NULL, NULL),
('foundations_only', 66, 'ابواب الشقق ( حديد )', NULL, NULL, NULL, NULL),
('foundations_only', 67, 'ابواب الغرف', NULL, NULL, NULL, NULL),
('foundations_only', 68, 'أعمدة الثاني  ( حدادة - نجارة - التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_only', 69, 'سقف الثاني  ( نجارة -حدادة -تمديدات - التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_only', 70, 'مباني الثاني', NULL, NULL, NULL, NULL),
('foundations_only', 71, 'تأسيس كهرباء', NULL, NULL, NULL, NULL),
('foundations_only', 72, 'تأسيس سباكة', NULL, NULL, NULL, NULL),
('foundations_only', 73, 'تأسيس دفاع مدني', NULL, NULL, NULL, NULL),
('foundations_only', 74, 'اختبار صرف التكييف', NULL, NULL, NULL, NULL),
('foundations_only', 75, 'اعمال الطرطشة وتركيب الشبك والزوايا  وتقفيل المواسير', NULL, NULL, NULL, NULL),
('foundations_only', 76, 'اللياسة الداخلية', NULL, NULL, NULL, NULL),
('foundations_only', 77, 'الجبس', NULL, NULL, NULL, NULL),
('foundations_only', 78, 'الدهان الاوجه الاولى', NULL, NULL, NULL, NULL),
('foundations_only', 79, 'عزل الحمامات والمطابخ', NULL, NULL, NULL, NULL),
('foundations_only', 80, 'بلاط الارضيات والحمامات والجدران', NULL, NULL, NULL, NULL),
('foundations_only', 81, 'ابواب الشقق ( حديد )', NULL, NULL, NULL, NULL),
('foundations_only', 82, 'ابواب الغرف', NULL, NULL, NULL, NULL),
('foundations_only', 83, 'أعمدة الملحق  ( حدادة - نجارة - التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_only', 84, 'سقف الملحق ( نجارة -حدادة -تمديدات - التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_only', 85, 'مباني الملحق', NULL, NULL, NULL, NULL),
('foundations_only', 86, 'تأسيس كهرباء', NULL, NULL, NULL, NULL),
('foundations_only', 87, 'تأسيس سباكة', NULL, NULL, NULL, NULL),
('foundations_only', 88, 'تأسيس دفاع مدني', NULL, NULL, NULL, NULL),
('foundations_only', 89, 'اختبار صرف التكييف', NULL, NULL, NULL, NULL),
('foundations_only', 90, 'اعمال الطرطشة وتركيب الشبك والزوايا  وتقفيل المواسير', NULL, NULL, NULL, NULL),
('foundations_only', 91, 'اللياسة الداخلية', NULL, NULL, NULL, NULL),
('foundations_only', 92, 'الجبس', NULL, NULL, NULL, NULL),
('foundations_only', 93, 'الدهان الاوجه الاولى', NULL, NULL, NULL, NULL),
('foundations_only', 94, 'عزل الحمامات والمطابخ', NULL, NULL, NULL, NULL),
('foundations_only', 95, 'بلاط الارضيات والحمامات والجدران', NULL, NULL, NULL, NULL),
('foundations_only', 96, 'ابواب الشقق ( حديد )', NULL, NULL, NULL, NULL),
('foundations_only', 97, 'ابواب الغرف', NULL, NULL, NULL, NULL),
('foundations_only', 98, 'السترة  والمقاليب', NULL, NULL, NULL, NULL),
('foundations_only', 99, 'رخام الممرات والادراج', NULL, NULL, NULL, NULL),
('foundations_only', 100, 'تاسيس الاضاء الخارجية', NULL, NULL, NULL, NULL),
('foundations_only', 101, 'اللياسة الخارجية', NULL, NULL, NULL, NULL),
('foundations_only', 102, 'الرشة الخارجية', NULL, NULL, NULL, NULL),
('foundations_only', 103, 'الالمنيوم', NULL, NULL, NULL, NULL),
('foundations_only', 104, 'وجه الدهان النهائي', NULL, NULL, NULL, NULL),
('foundations_only', 105, 'حماية الشبابيك', NULL, NULL, NULL, NULL),
('foundations_only', 106, 'اكسسوارات السباكة', NULL, NULL, NULL, NULL),
('foundations_only', 107, 'اكسسوارات الكهرباء', NULL, NULL, NULL, NULL),
('foundations_only', 108, 'صبة حول المواسير', NULL, NULL, NULL, NULL),
('foundations_only', 109, 'عزل الاسطح', NULL, NULL, NULL, NULL),
('foundations_only', 110, 'تمديد المواسير والكيبلات', NULL, NULL, NULL, NULL),
('foundations_only', 111, 'بلاط الاسطح', NULL, NULL, NULL, NULL),
('foundations_only', 112, 'تمديد الكيبل بالباركينج', NULL, NULL, NULL, NULL),
('foundations_only', 113, 'تمديد مواسير الخزانات بالباركينج', NULL, NULL, NULL, NULL),
('foundations_only', 114, 'صبة الباركينج', NULL, NULL, NULL, NULL),
('foundations_only', 115, 'البردورا والانترلوك', NULL, NULL, NULL, NULL),
('foundations_only', 116, 'الاسفلت', NULL, NULL, NULL, NULL),
('foundations_only', 117, 'ايبوكسي وتخطيط الباركينج', NULL, NULL, NULL, NULL),
('foundations_only', 118, 'الجلي', NULL, NULL, NULL, NULL),
('foundations_only', 119, 'تقفيل ملاحظات', NULL, NULL, NULL, NULL),
('foundations_basement', 1, 'شراء الارض', '2026-06-30', NULL, NULL, NULL),
('foundations_basement', 2, 'الصك', NULL, NULL, NULL, NULL),
('foundations_basement', 3, 'اعمال الرفع المساحي حدود ومناسيب الشارع', NULL, NULL, NULL, NULL),
('foundations_basement', 4, 'السور المؤقت', NULL, NULL, NULL, NULL),
('foundations_basement', 5, 'جسات التربة', NULL, NULL, NULL, NULL),
('foundations_basement', 6, 'مرحلة التخطيط والتصميم والرخصة', NULL, NULL, NULL, NULL),
('foundations_basement', 7, 'مرحلة حفر الارض للوصول الى منسوب التصميم', NULL, NULL, NULL, NULL),
('foundations_basement', 8, 'أعمال حفر - الخزانات والبيارات', NULL, NULL, NULL, NULL),
('foundations_basement', 9, 'مرحلة الاحلال  والرص والاختبارات + اختبار التحميل اللوحي', NULL, NULL, NULL, NULL),
('foundations_basement', 10, 'صبة نظافة الخزانات والبيارات', NULL, NULL, NULL, NULL),
('foundations_basement', 11, 'مباني الخزانات والبيارات', NULL, NULL, NULL, NULL),
('foundations_basement', 12, 'عزل الخزانات والبيارات', NULL, NULL, NULL, NULL),
('foundations_basement', 13, 'صبة اللبشة خزانات والبيارات', NULL, NULL, NULL, NULL),
('foundations_basement', 14, 'الدفان حول جدران الخزانات والبيارات', NULL, NULL, NULL, NULL),
('foundations_basement', 15, 'صبة جدران الخزانات والبيارات', NULL, NULL, NULL, NULL),
('foundations_basement', 16, 'صبة سقف الخزانات والبيارات', NULL, NULL, NULL, NULL),
('foundations_basement', 17, 'استكمال احلال الموقع في الاماكن المجاورة للخزانات والبيارات', NULL, NULL, NULL, NULL),
('foundations_basement', 18, 'اعمال الرص وصبة النظافة', NULL, NULL, NULL, NULL),
('foundations_basement', 19, 'اعمال المباني لبشة القبو', NULL, NULL, NULL, NULL),
('foundations_basement', 20, 'اعمال العزل لبشة القبو', NULL, NULL, NULL, NULL),
('foundations_basement', 21, 'اعمال حدادة اللبشة - والتمديدات الميكانيكية ةتسليم التأمين', NULL, NULL, NULL, NULL),
('foundations_basement', 22, 'اعمال صبة اللبشة للقبو', NULL, NULL, NULL, NULL),
('foundations_basement', 23, 'اعمال صبة اعمدة وجدران للقبو', NULL, NULL, NULL, NULL),
('foundations_basement', 24, 'اعمال صبة سقف القبو', NULL, NULL, NULL, NULL),
('foundations_basement', 25, 'اعمال عزل جدران القبو وبناء بلوك الحماية', NULL, NULL, NULL, NULL),
('foundations_basement', 26, 'اعمال الدفان حول القبو', NULL, NULL, NULL, NULL),
('foundations_basement', 27, 'صبة القواعد  ( نجارة حدادة -التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_basement', 28, 'صبة الرقاب ( نجارة حدادة صب )', NULL, NULL, NULL, NULL),
('foundations_basement', 29, 'العزل قواعد ورقاب', NULL, NULL, NULL, NULL),
('foundations_basement', 30, 'الدفان ( شامل التوريد والرص والمختبر والتسليم )', NULL, NULL, NULL, NULL),
('foundations_basement', 31, 'مباني كرسي الميدا - مع عزله من الاعلى بلفائف عزل', NULL, NULL, NULL, NULL),
('foundations_basement', 32, 'صبة الميدا ( نجارة حدادة -التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_basement', 33, 'فك الميدا', NULL, NULL, NULL, NULL),
('foundations_basement', 34, 'عزل الميدا', NULL, NULL, NULL, NULL),
('foundations_basement', 35, 'تمديدات الالكتروميكانية ( مع الاختبارات والتثبيت )', NULL, NULL, NULL, NULL),
('foundations_basement', 36, 'الدفان بين الميدات   (شامل التوريد والرص والمختبر والتأمين )', NULL, NULL, NULL, NULL),
('foundations_basement', 37, 'صبة الارضية بين الميدات ( رش مبيد بلاستيك حدادة صب )', NULL, NULL, NULL, NULL),
('foundations_basement', 38, 'أعمدة الأرضي ( حدادة - نجارة - التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_basement', 39, 'اسقف الأرضي  ( نجارة -حدادة -تمديدات - التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_basement', 40, 'مباني الأرضي', NULL, NULL, NULL, NULL),
('foundations_basement', 41, 'تأسيس كهرباء - قبل اللياسة', NULL, NULL, NULL, NULL),
('foundations_basement', 42, 'تأسيس سباكة - قبل اللياسة', NULL, NULL, NULL, NULL),
('foundations_basement', 43, 'تأسيس دفاع مدني - قبل اللياسة', NULL, NULL, NULL, NULL),
('foundations_basement', 44, 'اختبار صرف التكييف - قبل اللياسة', NULL, NULL, NULL, NULL),
('foundations_basement', 45, 'اعمال الطرطشة وتركيب الشبك والزوايا  وتقفيل المواسير', NULL, NULL, NULL, NULL),
('foundations_basement', 46, 'اللياسة الداخلية', NULL, NULL, NULL, NULL),
('foundations_basement', 47, 'الجبس', NULL, NULL, NULL, NULL),
('foundations_basement', 48, 'الدهان الاوجه الاولى', NULL, NULL, NULL, NULL),
('foundations_basement', 49, 'عزل الحمامات والمطابخ', NULL, NULL, NULL, NULL),
('foundations_basement', 50, 'بلاط الارضيات والحمامات والجدران', NULL, NULL, NULL, NULL),
('foundations_basement', 51, 'ابواب الشقق ( حديد )', NULL, NULL, NULL, NULL),
('foundations_basement', 52, 'ابواب الغرف', NULL, NULL, NULL, NULL),
('foundations_basement', 53, 'أعمدة الأول ( حدادة - نجارة - التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_basement', 54, 'سقف الأول  ( نجارة -حدادة -تمديدات - التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_basement', 55, 'مباني الأول', NULL, NULL, NULL, NULL),
('foundations_basement', 56, 'تأسيس كهرباء', NULL, NULL, NULL, NULL),
('foundations_basement', 57, 'تأسيس سباكة', NULL, NULL, NULL, NULL),
('foundations_basement', 58, 'تأسيس دفاع مدني', NULL, NULL, NULL, NULL),
('foundations_basement', 59, 'اختبار صرف التكييف', NULL, NULL, NULL, NULL),
('foundations_basement', 60, 'اعمال الطرطشة وتركيب الشبك والزوايا  وتقفيل المواسير', NULL, NULL, NULL, NULL),
('foundations_basement', 61, 'اللياسة الداخلية', NULL, NULL, NULL, NULL),
('foundations_basement', 62, 'الجبس', NULL, NULL, NULL, NULL),
('foundations_basement', 63, 'الدهان الاوجه الاولى', NULL, NULL, NULL, NULL),
('foundations_basement', 64, 'عزل الحمامات والمطابخ', NULL, NULL, NULL, NULL),
('foundations_basement', 65, 'بلاط الارضيات والحمامات والجدران', NULL, NULL, NULL, NULL),
('foundations_basement', 66, 'ابواب الشقق ( حديد )', NULL, NULL, NULL, NULL),
('foundations_basement', 67, 'ابواب الغرف', NULL, NULL, NULL, NULL),
('foundations_basement', 68, 'أعمدة الثاني  ( حدادة - نجارة - التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_basement', 69, 'سقف الثاني  ( نجارة -حدادة -تمديدات - التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_basement', 70, 'مباني الثاني', NULL, NULL, NULL, NULL),
('foundations_basement', 71, 'تأسيس كهرباء', NULL, NULL, NULL, NULL),
('foundations_basement', 72, 'تأسيس سباكة', NULL, NULL, NULL, NULL),
('foundations_basement', 73, 'تأسيس دفاع مدني', NULL, NULL, NULL, NULL),
('foundations_basement', 74, 'اختبار صرف التكييف', NULL, NULL, NULL, NULL),
('foundations_basement', 75, 'اعمال الطرطشة وتركيب الشبك والزوايا  وتقفيل المواسير', NULL, NULL, NULL, NULL),
('foundations_basement', 76, 'اللياسة الداخلية', NULL, NULL, NULL, NULL),
('foundations_basement', 77, 'الجبس', NULL, NULL, NULL, NULL),
('foundations_basement', 78, 'الدهان الاوجه الاولى', NULL, NULL, NULL, NULL),
('foundations_basement', 79, 'عزل الحمامات والمطابخ', NULL, NULL, NULL, NULL),
('foundations_basement', 80, 'بلاط الارضيات والحمامات والجدران', NULL, NULL, NULL, NULL),
('foundations_basement', 81, 'ابواب الشقق ( حديد )', NULL, NULL, NULL, NULL),
('foundations_basement', 82, 'ابواب الغرف', NULL, NULL, NULL, NULL),
('foundations_basement', 83, 'أعمدة الملحق  ( حدادة - نجارة - التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_basement', 84, 'سقف الملحق ( نجارة -حدادة -تمديدات - التأمين - صب )', NULL, NULL, NULL, NULL),
('foundations_basement', 85, 'مباني الملحق', NULL, NULL, NULL, NULL),
('foundations_basement', 86, 'تأسيس كهرباء', NULL, NULL, NULL, NULL),
('foundations_basement', 87, 'تأسيس سباكة', NULL, NULL, NULL, NULL),
('foundations_basement', 88, 'تأسيس دفاع مدني', NULL, NULL, NULL, NULL),
('foundations_basement', 89, 'اختبار صرف التكييف', NULL, NULL, NULL, NULL),
('foundations_basement', 90, 'اعمال الطرطشة وتركيب الشبك والزوايا  وتقفيل المواسير', NULL, NULL, NULL, NULL),
('foundations_basement', 91, 'اللياسة الداخلية', NULL, NULL, NULL, NULL),
('foundations_basement', 92, 'الجبس', NULL, NULL, NULL, NULL),
('foundations_basement', 93, 'الدهان الاوجه الاولى', NULL, NULL, NULL, NULL),
('foundations_basement', 94, 'عزل الحمامات والمطابخ', NULL, NULL, NULL, NULL),
('foundations_basement', 95, 'بلاط الارضيات والحمامات والجدران', NULL, NULL, NULL, NULL),
('foundations_basement', 96, 'ابواب الشقق ( حديد )', NULL, NULL, NULL, NULL),
('foundations_basement', 97, 'ابواب الغرف', NULL, NULL, NULL, NULL),
('foundations_basement', 98, 'السترة  والمقاليب', NULL, NULL, NULL, NULL),
('foundations_basement', 99, 'رخام الممرات والادراج', NULL, NULL, NULL, NULL),
('foundations_basement', 100, 'تاسيس الاضاء الخارجية', NULL, NULL, NULL, NULL),
('foundations_basement', 101, 'اللياسة الخارجية', NULL, NULL, NULL, NULL),
('foundations_basement', 102, 'الرشة الخارجية', NULL, NULL, NULL, NULL),
('foundations_basement', 103, 'الالمنيوم', NULL, NULL, NULL, NULL),
('foundations_basement', 104, 'وجه الدهان النهائي', NULL, NULL, NULL, NULL),
('foundations_basement', 105, 'حماية الشبابيك', NULL, NULL, NULL, NULL),
('foundations_basement', 106, 'اكسسوارات السباكة', NULL, NULL, NULL, NULL),
('foundations_basement', 107, 'اكسسوارات الكهرباء', NULL, NULL, NULL, NULL),
('foundations_basement', 108, 'صبة حول المواسير', NULL, NULL, NULL, NULL),
('foundations_basement', 109, 'عزل الاسطح', NULL, NULL, NULL, NULL),
('foundations_basement', 110, 'تمديد المواسير والكيبلات', NULL, NULL, NULL, NULL),
('foundations_basement', 111, 'بلاط الاسطح', NULL, NULL, NULL, NULL),
('foundations_basement', 112, 'تمديد الكيبل بالباركينج', NULL, NULL, NULL, NULL),
('foundations_basement', 113, 'تمديد مواسير الخزانات بالباركينج', NULL, NULL, NULL, NULL),
('foundations_basement', 114, 'صبة الباركينج', NULL, NULL, NULL, NULL),
('foundations_basement', 115, 'البردورا والانترلوك', NULL, NULL, NULL, NULL),
('foundations_basement', 116, 'الاسفلت', NULL, NULL, NULL, NULL),
('foundations_basement', 117, 'ايبوكسي وتخطيط الباركينج', NULL, NULL, NULL, NULL),
('foundations_basement', 118, 'الجلي', NULL, NULL, NULL, NULL),
('foundations_basement', 119, 'تقفيل ملاحظات', NULL, NULL, NULL, NULL),
('basement_only', 1, 'شراء الارض', '2026-06-30', NULL, NULL, NULL),
('basement_only', 2, 'الصك', NULL, NULL, NULL, NULL),
('basement_only', 3, 'اعمال الرفع المساحي حدود ومناسيب الشارع', NULL, NULL, NULL, NULL),
('basement_only', 4, 'السور المؤقت', NULL, NULL, NULL, NULL),
('basement_only', 5, 'جسات التربة', NULL, NULL, NULL, NULL),
('basement_only', 6, 'مرحلة التخطيط والتصميم والرخصة', NULL, NULL, NULL, NULL),
('basement_only', 7, 'مرحلة حفر الارض للوصول الى منسوب التصميم', NULL, NULL, NULL, NULL),
('basement_only', 8, 'أعمال حفر - الخزانات والبيارات', NULL, NULL, NULL, NULL),
('basement_only', 9, 'مرحلة الاحلال  والرص والاختبارات + اختبار التحميل اللوحي', NULL, NULL, NULL, NULL),
('basement_only', 10, 'صبة نظافة الخزانات والبيارات', NULL, NULL, NULL, NULL),
('basement_only', 11, 'مباني الخزانات والبيارات', NULL, NULL, NULL, NULL),
('basement_only', 12, 'عزل الخزانات والبيارات', NULL, NULL, NULL, NULL),
('basement_only', 13, 'صبة اللبشة خزانات والبيارات', NULL, NULL, NULL, NULL),
('basement_only', 14, 'الدفان حول جدران الخزانات والبيارات', NULL, NULL, NULL, NULL),
('basement_only', 15, 'صبة جدران الخزانات والبيارات', NULL, NULL, NULL, NULL),
('basement_only', 16, 'صبة سقف الخزانات والبيارات', NULL, NULL, NULL, NULL),
('basement_only', 17, 'استكمال احلال الموقع في الاماكن المجاورة للخزانات والبيارات', NULL, NULL, NULL, NULL),
('basement_only', 18, 'اعمال الرص وصبة النظافة', NULL, NULL, NULL, NULL),
('basement_only', 19, 'اعمال المباني لبشة القبو', NULL, NULL, NULL, NULL),
('basement_only', 20, 'اعمال العزل لبشة القبو', NULL, NULL, NULL, NULL),
('basement_only', 21, 'اعمال حدادة اللبشة - والتمديدات الميكانيكية ةتسليم التأمين', NULL, NULL, NULL, NULL),
('basement_only', 22, 'اعمال صبة اللبشة للقبو', NULL, NULL, NULL, NULL),
('basement_only', 23, 'اعمال صبة اعمدة وجدران للقبو', NULL, NULL, NULL, NULL),
('basement_only', 24, 'اعمال صبة سقف القبو', NULL, NULL, NULL, NULL),
('basement_only', 25, 'اعمال عزل جدران القبو وبناء بلوك الحماية', NULL, NULL, NULL, NULL),
('basement_only', 26, 'اعمال الدفان حول القبو', NULL, NULL, NULL, NULL),
('basement_only', 27, 'صبة القواعد  ( نجارة حدادة -التأمين - صب )', NULL, NULL, NULL, NULL),
('basement_only', 28, 'صبة الرقاب ( نجارة حدادة صب )', NULL, NULL, NULL, NULL),
('basement_only', 29, 'العزل قواعد ورقاب', NULL, NULL, NULL, NULL),
('basement_only', 30, 'الدفان ( شامل التوريد والرص والمختبر والتسليم )', NULL, NULL, NULL, NULL),
('basement_only', 31, 'مباني كرسي الميدا - مع عزله من الاعلى بلفائف عزل', NULL, NULL, NULL, NULL),
('basement_only', 32, 'صبة الميدا ( نجارة حدادة -التأمين - صب )', NULL, NULL, NULL, NULL),
('basement_only', 33, 'فك الميدا', NULL, NULL, NULL, NULL),
('basement_only', 34, 'عزل الميدا', NULL, NULL, NULL, NULL),
('basement_only', 35, 'تمديدات الالكتروميكانية ( مع الاختبارات والتثبيت )', NULL, NULL, NULL, NULL),
('basement_only', 36, 'الدفان بين الميدات   (شامل التوريد والرص والمختبر والتأمين )', NULL, NULL, NULL, NULL),
('basement_only', 37, 'صبة الارضية بين الميدات ( رش مبيد بلاستيك حدادة صب )', NULL, NULL, NULL, NULL),
('basement_only', 38, 'أعمدة الأرضي ( حدادة - نجارة - التأمين - صب )', NULL, NULL, NULL, NULL),
('basement_only', 39, 'اسقف الأرضي  ( نجارة -حدادة -تمديدات - التأمين - صب )', NULL, NULL, NULL, NULL),
('basement_only', 40, 'مباني الأرضي', NULL, NULL, NULL, NULL),
('basement_only', 41, 'تأسيس كهرباء - قبل اللياسة', NULL, NULL, NULL, NULL),
('basement_only', 42, 'تأسيس سباكة - قبل اللياسة', NULL, NULL, NULL, NULL),
('basement_only', 43, 'تأسيس دفاع مدني - قبل اللياسة', NULL, NULL, NULL, NULL),
('basement_only', 44, 'اختبار صرف التكييف - قبل اللياسة', NULL, NULL, NULL, NULL),
('basement_only', 45, 'اعمال الطرطشة وتركيب الشبك والزوايا  وتقفيل المواسير', NULL, NULL, NULL, NULL),
('basement_only', 46, 'اللياسة الداخلية', NULL, NULL, NULL, NULL),
('basement_only', 47, 'الجبس', NULL, NULL, NULL, NULL),
('basement_only', 48, 'الدهان الاوجه الاولى', NULL, NULL, NULL, NULL),
('basement_only', 49, 'عزل الحمامات والمطابخ', NULL, NULL, NULL, NULL),
('basement_only', 50, 'بلاط الارضيات والحمامات والجدران', NULL, NULL, NULL, NULL),
('basement_only', 51, 'ابواب الشقق ( حديد )', NULL, NULL, NULL, NULL),
('basement_only', 52, 'ابواب الغرف', NULL, NULL, NULL, NULL),
('basement_only', 53, 'أعمدة الأول ( حدادة - نجارة - التأمين - صب )', NULL, NULL, NULL, NULL),
('basement_only', 54, 'سقف الأول  ( نجارة -حدادة -تمديدات - التأمين - صب )', NULL, NULL, NULL, NULL),
('basement_only', 55, 'مباني الأول', NULL, NULL, NULL, NULL),
('basement_only', 56, 'تأسيس كهرباء', NULL, NULL, NULL, NULL),
('basement_only', 57, 'تأسيس سباكة', NULL, NULL, NULL, NULL),
('basement_only', 58, 'تأسيس دفاع مدني', NULL, NULL, NULL, NULL),
('basement_only', 59, 'اختبار صرف التكييف', NULL, NULL, NULL, NULL),
('basement_only', 60, 'اعمال الطرطشة وتركيب الشبك والزوايا  وتقفيل المواسير', NULL, NULL, NULL, NULL),
('basement_only', 61, 'اللياسة الداخلية', NULL, NULL, NULL, NULL),
('basement_only', 62, 'الجبس', NULL, NULL, NULL, NULL),
('basement_only', 63, 'الدهان الاوجه الاولى', NULL, NULL, NULL, NULL),
('basement_only', 64, 'عزل الحمامات والمطابخ', NULL, NULL, NULL, NULL),
('basement_only', 65, 'بلاط الارضيات والحمامات والجدران', NULL, NULL, NULL, NULL),
('basement_only', 66, 'ابواب الشقق ( حديد )', NULL, NULL, NULL, NULL),
('basement_only', 67, 'ابواب الغرف', NULL, NULL, NULL, NULL),
('basement_only', 68, 'أعمدة الثاني  ( حدادة - نجارة - التأمين - صب )', NULL, NULL, NULL, NULL),
('basement_only', 69, 'سقف الثاني  ( نجارة -حدادة -تمديدات - التأمين - صب )', NULL, NULL, NULL, NULL),
('basement_only', 70, 'مباني الثاني', NULL, NULL, NULL, NULL),
('basement_only', 71, 'تأسيس كهرباء', NULL, NULL, NULL, NULL),
('basement_only', 72, 'تأسيس سباكة', NULL, NULL, NULL, NULL),
('basement_only', 73, 'تأسيس دفاع مدني', NULL, NULL, NULL, NULL),
('basement_only', 74, 'اختبار صرف التكييف', NULL, NULL, NULL, NULL),
('basement_only', 75, 'اعمال الطرطشة وتركيب الشبك والزوايا  وتقفيل المواسير', NULL, NULL, NULL, NULL),
('basement_only', 76, 'اللياسة الداخلية', NULL, NULL, NULL, NULL),
('basement_only', 77, 'الجبس', NULL, NULL, NULL, NULL),
('basement_only', 78, 'الدهان الاوجه الاولى', NULL, NULL, NULL, NULL),
('basement_only', 79, 'عزل الحمامات والمطابخ', NULL, NULL, NULL, NULL),
('basement_only', 80, 'بلاط الارضيات والحمامات والجدران', NULL, NULL, NULL, NULL),
('basement_only', 81, 'ابواب الشقق ( حديد )', NULL, NULL, NULL, NULL),
('basement_only', 82, 'ابواب الغرف', NULL, NULL, NULL, NULL),
('basement_only', 83, 'أعمدة الملحق  ( حدادة - نجارة - التأمين - صب )', NULL, NULL, NULL, NULL),
('basement_only', 84, 'سقف الملحق ( نجارة -حدادة -تمديدات - التأمين - صب )', NULL, NULL, NULL, NULL),
('basement_only', 85, 'مباني الملحق', NULL, NULL, NULL, NULL),
('basement_only', 86, 'تأسيس كهرباء', NULL, NULL, NULL, NULL),
('basement_only', 87, 'تأسيس سباكة', NULL, NULL, NULL, NULL),
('basement_only', 88, 'تأسيس دفاع مدني', NULL, NULL, NULL, NULL),
('basement_only', 89, 'اختبار صرف التكييف', NULL, NULL, NULL, NULL),
('basement_only', 90, 'اعمال الطرطشة وتركيب الشبك والزوايا  وتقفيل المواسير', NULL, NULL, NULL, NULL),
('basement_only', 91, 'اللياسة الداخلية', NULL, NULL, NULL, NULL),
('basement_only', 92, 'الجبس', NULL, NULL, NULL, NULL),
('basement_only', 93, 'الدهان الاوجه الاولى', NULL, NULL, NULL, NULL),
('basement_only', 94, 'عزل الحمامات والمطابخ', NULL, NULL, NULL, NULL),
('basement_only', 95, 'بلاط الارضيات والحمامات والجدران', NULL, NULL, NULL, NULL),
('basement_only', 96, 'ابواب الشقق ( حديد )', NULL, NULL, NULL, NULL),
('basement_only', 97, 'ابواب الغرف', NULL, NULL, NULL, NULL),
('basement_only', 98, 'السترة  والمقاليب', NULL, NULL, NULL, NULL),
('basement_only', 99, 'رخام الممرات والادراج', NULL, NULL, NULL, NULL),
('basement_only', 100, 'تاسيس الاضاء الخارجية', NULL, NULL, NULL, NULL),
('basement_only', 101, 'اللياسة الخارجية', NULL, NULL, NULL, NULL),
('basement_only', 102, 'الرشة الخارجية', NULL, NULL, NULL, NULL),
('basement_only', 103, 'الالمنيوم', NULL, NULL, NULL, NULL),
('basement_only', 104, 'وجه الدهان النهائي', NULL, NULL, NULL, NULL),
('basement_only', 105, 'حماية الشبابيك', NULL, NULL, NULL, NULL),
('basement_only', 106, 'اكسسوارات السباكة', NULL, NULL, NULL, NULL),
('basement_only', 107, 'اكسسوارات الكهرباء', NULL, NULL, NULL, NULL),
('basement_only', 108, 'صبة حول المواسير', NULL, NULL, NULL, NULL),
('basement_only', 109, 'عزل الاسطح', NULL, NULL, NULL, NULL),
('basement_only', 110, 'تمديد المواسير والكيبلات', NULL, NULL, NULL, NULL),
('basement_only', 111, 'بلاط الاسطح', NULL, NULL, NULL, NULL),
('basement_only', 112, 'تمديد الكيبل بالباركينج', NULL, NULL, NULL, NULL),
('basement_only', 113, 'تمديد مواسير الخزانات بالباركينج', NULL, NULL, NULL, NULL),
('basement_only', 114, 'صبة الباركينج', NULL, NULL, NULL, NULL),
('basement_only', 115, 'البردورا والانترلوك', NULL, NULL, NULL, NULL),
('basement_only', 116, 'الاسفلت', NULL, NULL, NULL, NULL),
('basement_only', 117, 'ايبوكسي وتخطيط الباركينج', NULL, NULL, NULL, NULL),
('basement_only', 118, 'الجلي', NULL, NULL, NULL, NULL),
('basement_only', 119, 'تقفيل ملاحظات', NULL, NULL, NULL, NULL);